INSERT INTO HOLDING VALUES('IBM',200);
INSERT INTO HOLDING VALUES('AAPL',400);
INSERT INTO HOLDING VALUES('X',50);
INSERT INTO HOLDING VALUES('CCC',1000);
INSERT INTO HOLDING VALUES('GM',500);
 
INSERT INTO MODEL VALUES('GM',20);
INSERT INTO MODEL VALUES('F',20);
INSERT INTO MODEL VALUES('X',10);
INSERT INTO MODEL VALUES('Y',50);